version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - CI_ENV=development
      - APP_BASE_URL=http://localhost:8080/
      - APP_KEY=please-change-me
    volumes:
      - .:/var/www/html
